//© Copyright 2018 Hewlett Packard Enterprise Development LP
//Licensed under Apache License version 2.0: http://www.apache.org/licenses/LICENSE-2.0

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.16 at 10:23:18 AM CET 
//


package com.hpe.simulap.sip.headers;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hp.simulap.sip.headers package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Headers_QNAME = new QName("http://www.hp.com/simulap/sip", "headers");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hp.simulap.sip.headers
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HeaderList }
     * 
     * @return HeaderList
     */
    public HeaderList createHeaderList() {
        return new HeaderList();
    }

    /**
     * Create an instance of {@link Header }
     * 
     * @return Header
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HeaderList }{@code >}} @
     * 
     * @param value HeaderList to be created as headers
     * @return HeaderList as JAXBElement
     */
    @XmlElementDecl(namespace = "http://www.hp.com/simulap/sip", name = "headers")
    public JAXBElement<HeaderList> createHeaders(HeaderList value) {
        return new JAXBElement<HeaderList>(_Headers_QNAME, HeaderList.class, null, value);
    }

}
